name: test-train-build

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest dvc

      - name: Lint code
        run: flake8 .

      - name: Run DVC pipeline
        run: dvc repro

      - name: Run tests
        run: pytest

      - name: Build Docker image
        run: docker build -t bank-marketing-api .